name: Run Daily at 16h Paris

on:
  schedule:
    - cron: '0 14 * * *'  # Tous les jours à 14h UTC (16h à Paris)
  workflow_dispatch:  # option manuelle

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run main script
        run: |
          python script/__main__.py
